// Auto-generated by BackEnd/run.py — do not edit by hand.
// Override before any other script tag if needed.
window.APP_CONFIG = window.APP_CONFIG || {
    API_BASE_URL: 'http://127.0.0.1:8000',
    HEALTH_PATH: '/health',
    EVENT_POLL_MS: 2000,
    HEALTH_INTERVAL_MS: 5000,
    RECOGNIZE_INTERVAL_MS: 800,
};
